development:
  stripe_publishable_key: pk_test_yaXO7enjZolLxejAqCvAtVao00pPAW38WV
  stripe_secret_key: sk_test_CRquBc4HJxYslxYlFbUi2Bi9006duVHqpj

production:
  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_publishable_key']